### ISSUE TITLE
Exporting the camera path?

### ISSUE THREAD

**Issue by graveyard99** [microsoft/MoGe#12]
If you are essentially registering each frame of the point cloud to create the static environment, are you also outputting the camera positions?

if there's no animated camera data it's not that useful.

FBX and Alembic formats would be great for this

**Comment by EasternJournalist** [comment]
Hi. The script of video reconstruction, which is an extension of MoGe, is not released yet.  We have currently released only the **Mo**nocular **Ge**ometry estimation inference code, which is the original purpose of **MoGe**.

These two issues might be related to your need, where you can find how we implemented the video reconstruction code. 

- https://github.com/microsoft/MoGe/issues/6
- https://github.com/microsoft/MoGe/issues/7

**Comment by graveyard99** [comment]
Kind of useful but not exactly what creatives need if they want to
accurately add object to a scene with matching perspective/parallax

Are you familiar with software like MetaShape, RealityCapture or PFTrack?

These all employ photogrammetric SFM algorithms to find camera positions
and enable the export of all aligned camera positions in a wide range of
file formats for VFX artists to derive camera tracks from

Kind Regards

Hayden Martin <https://www.haydenmart.in/>

Instagram <https://www.instagram.com/_hayden_martin_/>
Vimeo <https://vimeo.com/haydenmartin>
LinkedIn <https://uk.linkedin.com/in/haydenmartincreative>
+44 07817281488

**Comment by EasternJournalist** [comment]
Thank you for your suggestions. We will consider and explore more about the community needs in our future research.
