### ISSUE TITLE
Recovery of point clouds from depth maps appears distorted

### ISSUE THREAD

**Issue by stan1512** [microsoft/MoGe#17]
great work , but i found the depth may be not good as the point cloud
The difference between the output point cloud and the point cloud recovered from the depth map is somewhat large.
![Image](https://github.com/user-attachments/assets/b3c20f7b-de15-4296-bb24-3357db7b6386)
>points from output

![Image](https://github.com/user-attachments/assets/9923b680-3d31-4df1-9a0b-04d48424e7c8)
> point from depth using the intrinsic from the inferrence

**Comment by EasternJournalist** [comment]
Hi. The output depth map is exactly the Z-channel of the point map.  Therefore, the point cloud recovered with the depth map (stored in `depth.exr`, not `depth.png`, which is only for visualization) and the FoVs in `fov.json` should be _identical_ to the point map `points.exr`. Can you please provide more details how you obtain the point cloud from depth?

**Comment by stan1512** [comment]
The distortion does not occur when I recover the point cloud by using the output output depth map directly instead of saving the output output depth as a png image, thanks for your work!

        depth = output["depth"].cpu().numpy()  
        mask = output["mask"].cpu().numpy()  
        intrinsics = output["intrinsics"].cpu().numpy()  

        fx = intrinsics[0, 0] * 1000
        fy = intrinsics[1, 1] * 1000
        cx = intrinsics[0, 2] * 1000
        cy = intrinsics[1, 2] * 1000

        x_valid = (u_valid - cx) * z_valid / fx
        y_valid = (v_valid - cy) * z_valid / fy
        points = np.stack((x_valid, y_valid, z_valid), axis=-1)
        colors = input_image.reshape(-1, 3) / 255.0
        pcd = o3d.geometry.PointCloud()
        pcd.points = o3d.utility.Vector3dVector(points)
        pcd.colors = o3d.utility.Vector3dVector(colors)
