### ISSUE TITLE
No dependency versioning

### ISSUE THREAD

**Issue by abhishek47kashyap** [microsoft/MoGe#21]
`requirements.txt` does not specify versions.
https://github.com/microsoft/MoGe/blob/3ecc61570bee338d717319ba60109a02756acc00/requirements.txt#L1-L7

This can cause issues when a dependency's next release becomes incompatible with another dependency.

**Comment by EasternJournalist** [comment]
Hi, thank you for your suggestions. We will consider adding recommended or minimum versions to the requirements file.

The reason we haven't specified strict or maximum dependency versions is that we aim to avoid forcing users to reinstall their native environment when installing our requirements. The packages we've selected, especially the features we use, are highly compatible and unlikely to introduce breaking changes in future versions.

However, if you encounter any incompatibilities with specific versions, please let us know so we can address them.
