### ISSUE TITLE
Question about the equation (17) in the paper

### ISSUE THREAD

**Issue by kakukakujirori** [microsoft/MoGe#22]
Thank you for your fascinating work. The result looks quite amazing.

It will be a minor point, but let me ask a question since I just wondered a bit. I'm struggling to wrap my head around the equation (17) in the supplementary material.

![Image](https://github.com/user-attachments/assets/25ff20a5-d1cc-4c25-939e-8ffa91119e19)

Although w_i and \hat{x}_i are positive from the assumption, x_i seems not guaranteed to be positive. I would appreciate it if you could explain why the second line to the third line holds. Thank you.

**Comment by kakukakujirori** [comment]
I'm sorry, it was my oversight. It is just a typo, and the correct equation is
```
= 2 \sum_{...} w_i \hat{x}_i - \sum _{...} w_i \hat{x}_i - \sum _{...} w_i \hat{x}_i
< 2 \sum_{...} w_i \hat{x}_i
```
Isn't it? I could understand it, closing the issue.

**Comment by EasternJournalist** [comment]
Yes, that's indeed a typo. I apologize for the confusion. The paper will be updated soon with clearer statements and more detailed algorithms.
