### ISSUE TITLE
The output depth map is relative or metric depth?

### ISSUE THREAD

**Issue by puyiwen** [microsoft/MoGe#23]

**Comment by maciejhalber** [comment]
The paper clearly states that the predicted point maps are affine invariant (i.e up to `s*p + t`). The network itself outputs scale invariant maps, so the value `d` in depth maps is given up to unknown scale factor `s`.

**Comment by EasternJournalist** [comment]
Thank you, @maciejhalber , for providing a clear and thorough answer to the question. I believe this resolves the issue.
