### ISSUE TITLE
Possible usage

### ISSUE THREAD

**Issue by luohao123** [microsoft/MoGe#4]
Hi, MoGe is amazing, looks like very close for real-world applications, what could possible using scenario for this?

**Comment by EasternJournalist** [comment]
Thank you for your interest!  
   
MoGe targets several scenarios:

- **Facilitating Vision-Based 3D Reconstruction:** MoGe serves as a robust geometric prior for 3D reconstruction, making it an excellent candidate for integration with techniques like COLMAP, NeRF, and Gaussian splatting. For instance, you might find [SparseNeRF](https://sparsenerf.github.io/) intriguing. Our [website](https://wangrc.site/MoGePage/) also showcases MoGe's potential in video reconstruction.  
   
- **Empowering Scene-Level Generation:** Recent studies have explored scene generation using monocular depth estimation and image diffusion models. Examples include [ivid](https://jeffreyxiang.github.io/ivid/), [Wonder Journey](https://kovenyu.com/wonderjourney/), and [Wonder World](https://kovenyu.com/wonderworld/).  
   
- **Creating Fantastic Multimedia Applications:** MoGe can enhance _3D photo effects_, such as those seen in [3D-Photo-Inpainting](https://shihmengli.github.io/3D-Photo-Inpainting/) and [AdaMPI](https://yxuhan.github.io/AdaMPI/), as well as _3D-aware image editing_ like [Diffusion Handles](https://diffusionhandles.github.io/) and [Diff3DEdit](https://wangrc.site/Diff3DEdit/). MoGe offers a significant improvement over traditional monocular depth estimation models, often overcoming the common bottlenecks in previous applications. 

- **Embodied AI & robotics** MoGe demonstrates a strong capability in understanding the 3D world, which is critical for embodied AI. Its potential to enhance 3D comprehension makes it a direction worth exploring in future researches.

**Comment by luohao123** [comment]
Thanks, hoping to see more applications using MoGe.
