### ISSUE TITLE
Could we use MoGe for multi view 3d reconstruction?

### ISSUE THREAD

**Issue by Jiakui** [microsoft/MoGe#7]
Dear author, 

Thanks for your great work!

Could we use MoGe for multi view 3d reconstruction , such as  a video taken around an object  ? 

What's the best practice, can you give me some suggestions ?  

Thanks!

**Comment by EasternJournalist** [comment]
Hi, thanks for your interest.

We believe that multiview reconstruction and video reconstruction would be fantastic applications for integrating MoGe. As mentioned in this [issue](https://github.com/microsoft/MoGe/issues/6) and shown on our website, we have showcased results on videos using a very straightforward implementation of registration.

I suggest looking into SLAM methods. One potential approach for integrating SLAM with MoGe could involve first obtaining poses and sparse points using SLAM, and then registering the dense points or mesh from MoGe to those sparse points, adhering to an as-rigid-as-possible constraint.

**Comment by nnop** [comment]
Thanks for the suggestions. How to add as-rigid-as-possible constraint? Could you provide more hints? @EasternJournalist

**Comment by sunshineywz123** [comment]
> Hi, thanks for your interest.
> 
> We believe that multiview reconstruction and video reconstruction would be fantastic applications for integrating MoGe. As mentioned in this [issue](https://github.com/microsoft/MoGe/issues/6) and shown on our website, we have showcased results on videos using a very straightforward implementation of registration.
> 
> I suggest looking into SLAM methods. One potential approach for integrating SLAM with MoGe could involve first obtaining poses and sparse points using SLAM, and then registering the dense points or mesh from MoGe to those sparse points, adhering to an as-rigid-as-possible constraint.
> 
> I hope it helps : )

In the autonomous driving scenario, I align the point cloud of each frame of moge2 with the lidar, render the point cloud video, but the rendered video shakes a lot and there are serious inconsistencies. Has anyone in the community run this alignment code and can show the corresponding input video output?

**Comment by DebasritaDigsfact** [comment]
In Moge2, how do I align the point cloud of multiple frames? The frames make a circular path somehow.
