### ISSUE TITLE
The comment lol

### ISSUE THREAD

**Issue by jimtsai23** [microsoft/MoGe#8]
https://github.com/microsoft/MoGe/blob/ebef57aff8eac850f2de2e243550e1e5780ecdb4/utils3d/io/colmap.py#L36
Nice work! Maybe you forget to remove this comment. It is somehow hilarious lol.

**Comment by EasternJournalist** [comment]
Sorry for

**Comment by EasternJournalist** [comment]
Apologies for our oversight during code review. The code in question originates from a third-party unofficial package. We will instantly remove it and meticulously review the rest of the code.
